const ADD_TO_CART = "ADD_TO_CART"
const REMOVE_FROM_CART = "REMOVE_FROM_CART"
const REMOVE_ALL_CART = "REMOVE_ALL_CART"
const ADD_QUANTITY = 'ADD_QUANTITY';
const SUB_QUANTITY = 'SUB_QUANTITY';

export {ADD_TO_CART,REMOVE_FROM_CART,REMOVE_ALL_CART,ADD_QUANTITY,SUB_QUANTITY}