const CREATE_CART        = "CREATE_CART"
const GET_CART           = "GET_CART"
const ADD_PRODUCT        = "ADD_PRODUCT"
const ADD_CART_ITEMS     = "ADD_CART_ITEMS"
const USER_LOGIN         = "USER_LOGIN"
const USER_LOGOUT        = "USER_LOGOUT"

export {CREATE_CART,GET_CART,ADD_PRODUCT,ADD_CART_ITEMS,USER_LOGIN,USER_LOGOUT}